export const exploracionesEndpoints = {
  muestras: "/api/exploraciones/muestras",
  muestrasTodas: "/api/exploraciones/muestras-todas",
  muestraById: (id: string) => `/api/exploraciones/muestras/${id}`,
  elementos: "/api/exploraciones/elementos",
  laboratorios: "/api/exploraciones/laboratorios",
  projects: "/api/projects",
  projectById: (id: number) => `/api/projects/${id}`,
  zones: "/api/zones",
  zoneById: (id: number) => `/api/zones/${id}`,
  drillholes: "/api/drillholes",
  drillholeById: (id: number) => `/api/drillholes/${id}`,
  intervals: "/api/intervals",
  intervalById: (id: number) => `/api/intervals/${id}`,
  assays: "/api/assays",
  assayById: (id: number) => `/api/assays/${id}`,
  lithologies: "/api/lithologies",
  lithologyById: (id: number) => `/api/lithologies/${id}`,
  qaqc: "/api/qaqc",
  qaqcById: (id: number) => `/api/qaqc/${id}`,
  resources: "/api/resources",
  resourceById: (id: number) => `/api/resources/${id}`,
  drillHoleSurveys: "/api/mining-exploration/drill-hole-surveys",
  drillHoleSurveyById: (id: number) => `/api/mining-exploration/drill-hole-surveys/${id}`,
  assayValues: "/api/mining-exploration/assay-values",
  assayValueById: (id: number) => `/api/mining-exploration/assay-values/${id}`,
  alterations: "/api/mining-exploration/alterations",
  alterationById: (id: number) => `/api/mining-exploration/alterations/${id}`,
  mineralizations: "/api/mining-exploration/mineralizations",
  mineralizationById: (id: number) => `/api/mining-exploration/mineralizations/${id}`,
  geologicalStructures: "/api/mining-exploration/geological-structures",
  geologicalStructureById: (id: number) => `/api/mining-exploration/geological-structures/${id}`,
  recoveries: "/api/mining-exploration/recoveries",
  recoveryById: (id: number) => `/api/mining-exploration/recoveries/${id}`,
  densities: "/api/mining-exploration/densities",
  densityById: (id: number) => `/api/mining-exploration/densities/${id}`,
  magneticSusceptibilities: "/api/mining-exploration/magnetic-susceptibilities",
  magneticSusceptibilityById: (id: number) =>
    `/api/mining-exploration/magnetic-susceptibilities/${id}`,
  significantIntercepts: "/api/mining-exploration/significant-intercepts",
  significantInterceptById: (id: number) => `/api/mining-exploration/significant-intercepts/${id}`,
  miningAreas: "/api/surface-exploration/mining-areas",
  miningAreaById: (id: string) => `/api/surface-exploration/mining-areas/${id}`,
  miningLevels: "/api/surface-exploration/mining-levels",
  miningLevelById: (id: string) => `/api/surface-exploration/mining-levels/${id}`,
  miningLabors: "/api/surface-exploration/mining-labors",
  miningLaborById: (id: string) => `/api/surface-exploration/mining-labors/${id}`,
  surfaceSamples: "/api/surface-exploration/samples",
  surfaceSamplesWithResults: "/api/surface-exploration/samples/with-results",
  surfaceSampleById: (id: string) => `/api/surface-exploration/samples/${id}`,
  surfaceLaboratories: "/api/surface-exploration/laboratories",
  surfaceLaboratoryById: (id: string) => `/api/surface-exploration/laboratories/${id}`,
  sampleLaboratories: "/api/surface-exploration/sample-laboratories",
  sampleLaboratoryById: (id: string) => `/api/surface-exploration/sample-laboratories/${id}`,
  surfaceElements: "/api/surface-exploration/elements",
  surfaceElementById: (id: string) => `/api/surface-exploration/elements/${id}`,
  sampleResults: "/api/surface-exploration/sample-results",
  sampleResultById: (id: string) => `/api/surface-exploration/sample-results/${id}`,
  sampleQaqc: "/api/surface-exploration/sample-qaqc",
  sampleQaqcById: (id: string) => `/api/surface-exploration/sample-qaqc/${id}`,
  miningExcelValidate: "/api/imports/mining-excel/validate",
  miningExcelExecute: "/api/imports/mining-excel/execute"
} as const;
