export const inventarioImportEndpoints = {
  catalogo: "/api/inventario-import/catalogo",
  stockInicial: "/api/inventario-import/stock-inicial",
  reiniciarStock: "/api/inventario-import/reiniciar-stock",
  recalcularStock: "/api/inventario-import/recalcular-stock",
  sincronizarStock: "/api/inventario-import/sincronizar-stock",
  cierreMes: "/api/inventario-import/cierre-mes",
  saldoMensual: "/api/inventario-import/saldo-mensual",
  saldoMensualInicializar: "/api/inventario-import/saldo-mensual/inicializar",
  saldoMensualPreview: "/api/inventario-import/saldo-mensual/preview",
  saldoMensualItem: "/api/inventario-import/saldo-mensual/item",
  saldoMensualById: (id: string | number) => `/api/inventario-import/saldo-mensual/${id}`,
  saldoMensualAjusteTotal: (id: string | number) =>
    `/api/inventario-import/saldo-mensual/${id}/ajuste-total`,
  saldoMensualAjusteInicialExcel: "/api/inventario-import/saldo-mensual/ajuste-inicial/excel",
  ajusteProductosMes: "/api/inventario-import/ajuste-productos-mes",
  ajustarPreciosSinIva: "/api/inventario-import/ajustar-precios-sin-iva",
  backfillCpp: "/api/backfill/cpp",
  diagnosticoPrecios: "/api/inventario-import/diagnostico-precios",
  diagnosticoSaldos: "/api/inventario-import/diagnostico-saldos",
  diagnosticoRedondeo: "/api/inventario-import/diagnostico-redondeo",
  fixRedondeo: "/api/inventario-import/fix-redondeo",
  limpiarMesPreview: "/api/inventario-import/limpiar-mes/preview",
  limpiarMes: "/api/inventario-import/limpiar-mes"
} as const;
