name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            GITHUB_SHA=${{ github.sha }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/marte-frontend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/marte-frontend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/systems/marte-mining/web-mining

            echo "📦 Versión actual:"
            CURRENT_VERSION=$(docker inspect --format='{{ index .Config.Labels "org.opencontainers.image.revision" }}' web-mining-frontend-1 || echo "none")
            echo $CURRENT_VERSION

            echo "🚀 Nueva versión: ${{ github.sha }}"

            export VERSION=${{ github.sha }}

            echo "⬇️ Pull nueva imagen..."
            docker compose pull frontend

            echo "🚀 Deploy nueva versión..."
            docker compose up -d

            echo "⏳ Esperando healthcheck..."
            sleep 15

            STATUS=$(docker inspect --format='{{.State.Health.Status}}' web-mining-frontend-1 || echo "starting")

            if [ "$STATUS" != "healthy" ]; then
              echo "❌ Falló deploy. Rollback..."

              if [ "$CURRENT_VERSION" != "none" ]; then
                export VERSION=$CURRENT_VERSION

                echo "🔙 Volviendo a versión anterior: $VERSION"
                docker compose up -d
              else
                echo "No hay versión anterior"
              fi
            else
              echo "Deploy exitoso"
            fi